version: '3.5'

services:
  training:
    build: ./ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model

  backend:
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model


  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000

volumes:
  imgs:
  model: